services:
  - type: web
    name: parental-control-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server_cloud.py
    envVars:
      - key: PORT
        value: 8080

